name: Deploy to Firebase

on:
  push:
    branches:
      - 'develop'
  workflow_dispatch:
  workflow_call:
    secrets:
      FIREBASE_APP_ID_INTERNAL:
        required: true
      FIREBASE_CLI_TOKEN:
          required: true
      # Token must have read access to all the submodule repositories
      GH_MOBILE_PAT:
        required: true

env:
  INITIAL_VERSION_CODE: ${{ 1000 }}

jobs:
  build:
    name: Upload apk to Firebase
    runs-on: [ self-hosted, ARM64, active-android ]
    environment: Alpha
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GH_MOBILE_PAT }}

      - name: Build Docker image
        run: |
          docker build --platform linux/arm64 -t tangem_ci_android_environment .

      - name: Increment version code
        env:
          RUN_NUMBER: ${{ github.run_number }}
        run: |
          echo "VERSION_CODE=$((RUN_NUMBER + $INITIAL_VERSION_CODE))" >> $GITHUB_ENV

      - name: Read version.properties file
        uses: BrycensRanch/read-properties-action@v1
        id: version
        with:
          file: version.properties
          property: versionName
          default: 0.0.1

      - name: Run uploading
        env:
          app_id_internal: ${{ secrets.FIREBASE_APP_ID_INTERNAL }}
          firebase_cli_token: ${{ secrets.FIREBASE_CLI_TOKEN }}
          apk_path_internal: app/build/outputs/apk/internal/app-internal.apk
          version_code: ${{ env.VERSION_CODE }}
          version_name: ${{ steps.version.outputs.versionName }}
          release_notes: ${{ github.ref_name }} - ${{ github.sha }}
          groups: testers
        run: |
          env > .env
          docker run --rm \
            --env-file .env \
            -v ~/.gradle:/root/.gradle \
            -v ${{ github.workspace }}:/workspace \
            tangem_ci_android_environment \
            sh -c "
              cd /workspace;
          
              echo 'Deploying APK to Firebase...';

              fastlane publishToFirebase;
            "
